"""
aa_skills.cli
================

Command-line entry point: `aa-skills`

Design notes:

- Every invocation targets a named *session* (default: "default").
  Sessions are how the CLI "maintains a list of files generated" —
  each session keeps a disk-persisted manifest of every output file,
  addressable later by a short alias.

- Passing a previously generated file into a later skill call is done
  with repeated `--use <alias>` flags, never by re-uploading or by
  pasting file content into the prompt. This is what keeps a multi-step
  chain (e.g. extract -> analyze -> generate deck) from re-inflating
  the context window on every step.

- `--new-session` explicitly starts a clean session (fresh container,
  empty file manifest). Without it, the named session is resumed as-is.
  This makes context growth an opt-in, visible decision rather than an
  accumulating default.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .registry import SkillRegistry, RegisteredSkill, register_custom_skill_from_dir
from .context import SessionContext
from .client import AASkillInvoker
from . import credits


def _print_warnings(warnings: list[str]) -> None:
    for w in warnings:
        print(f"[warning] {w}", file=sys.stderr)


def cmd_invoke(args: argparse.Namespace) -> None:
    if bool(args.prompt) == bool(args.prompt_file):
        print("Specify exactly one of --prompt or --prompt-file.", file=sys.stderr)
        sys.exit(2)
    if args.prompt_file:
        prompt_path = Path(args.prompt_file)
        if not prompt_path.exists():
            print(f"Prompt file not found: {prompt_path}", file=sys.stderr)
            sys.exit(2)
        prompt_text = prompt_path.read_text(encoding="utf-8")
    else:
        prompt_text = args.prompt

    registry = SkillRegistry(path=args.registry)
    session = (
        SessionContext(session_name=args.session)
        if args.new_session
        else SessionContext.load_or_create(args.session, session_dir=args.session_dir)
    )

    invoker = AASkillInvoker(
        api_key=args.api_key,
        registry=registry,
        model=args.model,
        output_dir=args.output_dir,
        credit_threshold_usd=args.credit_threshold,
    )

    result = invoker.invoke(
        prompt=prompt_text,
        skill_names=args.skills,
        session=session,
        new_input_files=args.file,
        use_generated=args.use,
        max_tokens=args.max_tokens,
        max_context_tokens=args.max_context_tokens,
        skip_credit_check=args.skip_credit_check,
        live_credit_probe=args.live_credit_probe,
    )

    _print_warnings(result.warnings)

    if not result.downloaded_files:
        print("No files were generated by this invocation.")
    for entry in result.downloaded_files:
        path = entry["path"]
        skill_label = "+".join(args.skills)
        description = args.describe or f"Output of skill(s) [{skill_label}] for prompt: {prompt_text[:80]}"
        gf = session.register_output(
            file_id=entry["file_id"],
            filename=path.name,
            produced_by_skill=skill_label,
            description=description,
        )
        print(f"Generated: {path}  (alias: {gf.alias})")

    session.save(session_dir=args.session_dir)
    print(f"\nSession '{session.session_name}' updated "
          f"({len(session.generated_files)} tracked file(s), "
          f"{session.turn_count} turn(s)).")


def cmd_list_skills(args: argparse.Namespace) -> None:
    registry = SkillRegistry(path=args.registry)
    skills = registry.list()
    if not skills:
        print("No skills registered. Run `aa-skills register-skill` or "
              "`aa-skills bootstrap` first.")
        return
    for s in skills:
        print(f"{s.name:30s} type={s.type:9s} version={s.version:20s} {s.description}")


def cmd_bootstrap(args: argparse.Namespace) -> None:
    registry = SkillRegistry.bootstrap_prebuilt(path=args.registry)
    print(f"Registered {len(registry.list())} pre-built Anthropic skills at {registry.path}")


def cmd_register_skill(args: argparse.Namespace) -> None:
    import anthropic

    client = anthropic.Anthropic(api_key=args.api_key) if args.api_key else anthropic.Anthropic()
    registry = SkillRegistry(path=args.registry)
    skill = register_custom_skill_from_dir(
        client=client,
        registry=registry,
        name=args.name,
        display_title=args.title,
        skill_dir=args.dir,
        description=args.description or "",
        typical_output_kind=args.output_kind,
    )
    print(f"Registered custom skill '{skill.name}' -> {skill.anthropic_skill_id} "
          f"(version {skill.version})")


def cmd_credits_set_balance(args: argparse.Namespace) -> None:
    api_key = args.api_key or __import__("os").environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("No API key provided (use --api-key or set ANTHROPIC_API_KEY).", file=sys.stderr)
        sys.exit(1)
    ledger = credits.set_initial_balance(api_key, args.amount)
    print(f"Set local balance estimate to ${args.amount:.2f}. "
          f"Estimated balance now: ${ledger.estimated_balance_usd:.2f}")


def cmd_credits_show(args: argparse.Namespace) -> None:
    api_key = args.api_key or __import__("os").environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("No API key provided (use --api-key or set ANTHROPIC_API_KEY).", file=sys.stderr)
        sys.exit(1)
    ledger = credits.CreditLedger.load(api_key)
    if ledger.initial_balance_usd is None:
        print("No balance has been set for this key. Run "
              "`aa-skills credits set-balance --amount <topped_up_usd>` first.")
        return
    print(f"Initial balance recorded:  ${ledger.initial_balance_usd:.2f}")
    print(f"Estimated spend so far:    ${ledger.cumulative_spend_usd:.4f}")
    print(f"Estimated balance now:     ${ledger.estimated_balance_usd:.2f}")
    print(f"Calls recorded:            {ledger.total_calls}")
    print("\nNote: this is a local estimate based on token usage priced against a "
          "static rate table — it is not fetched from Anthropic. Confirm anything "
          "you're relying on financially at console.anthropic.com/settings/billing.")


def cmd_credits_verify(args: argparse.Namespace) -> None:
    import anthropic

    api_key = args.api_key or __import__("os").environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("No API key provided (use --api-key or set ANTHROPIC_API_KEY).", file=sys.stderr)
        sys.exit(1)
    client = anthropic.Anthropic(api_key=api_key)
    status = credits.verify_key_and_check_credits(
        client=client,
        api_key=api_key,
        threshold_usd=args.credit_threshold,
        live_probe=True,
    )
    print(f"key_valid:              {status.key_valid}")
    print(f"estimated_balance_usd:  {status.estimated_balance_usd}")
    print(f"below_threshold:        {status.below_threshold} (threshold=${status.threshold_usd:.2f})")
    print(f"source:                 {status.source}")
    for w in status.warnings:
        print(f"[warning] {w}")


def cmd_files_list(args: argparse.Namespace) -> None:
    session = SessionContext.load_or_create(args.session, session_dir=args.session_dir)
    if not session.generated_files:
        print(f"No generated files tracked in session '{args.session}'.")
        return
    for gf in session.generated_files:
        print(gf.manifest_line())


def cmd_session_show(args: argparse.Namespace) -> None:
    session = SessionContext.load_or_create(args.session, session_dir=args.session_dir)
    print(f"session:       {session.session_name}")
    print(f"container_id:  {session.container_id}")
    print(f"turn_count:    {session.turn_count}")
    print(f"files tracked: {len(session.generated_files)}")
    print(f"context budget:{session.max_context_tokens} tokens")


def cmd_session_reset(args: argparse.Namespace) -> None:
    session = SessionContext.load_or_create(args.session, session_dir=args.session_dir)
    session.reset(session_dir=args.session_dir)
    print(f"Session '{args.session}' reset (container cleared, file manifest cleared).")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="aa-skills", description="Invoke AA-native skills via the Claude API.")
    p.add_argument("--registry", default=None, help="Path to the skill registry JSON file.")
    p.add_argument("--session-dir", default=None, help="Directory for session state files.")
    p.add_argument("--api-key", default=None, help="Anthropic API key (else ANTHROPIC_API_KEY env var).")
    sub = p.add_subparsers(dest="command", required=True)

    p_invoke = sub.add_parser("invoke", help="Invoke one or more skills.")
    p_invoke.add_argument("--skills", nargs="+", required=True, help="AA skill names to invoke (max 8).")
    p_invoke.add_argument("--prompt", default=None, help="Task instruction for Claude (inline string).")
    p_invoke.add_argument("--prompt-file", default=None,
                           help="Path to a text file containing the task instruction. Use for long "
                                "prompts — avoids Windows/shell command-line length limits. "
                                "Exactly one of --prompt / --prompt-file is required.")
    p_invoke.add_argument("--file", action="append", default=[], help="Local file to upload as input (repeatable).")
    p_invoke.add_argument("--use", action="append", default=[], help="Alias/filename of a previously generated file to reuse (repeatable).")
    p_invoke.add_argument("--session", default="default", help="Session name (default: 'default').")
    p_invoke.add_argument("--new-session", action="store_true", help="Start a fresh session instead of resuming.")
    p_invoke.add_argument("--model", default="claude-opus-4-8")
    p_invoke.add_argument("--max-tokens", type=int, default=8000)
    p_invoke.add_argument("--max-context-tokens", type=int, default=None,
                           help="Override the session's manifest/prompt token budget for this call.")
    p_invoke.add_argument("--describe", default=None, help="Description to attach to files generated by this call.")
    p_invoke.add_argument("--output-dir", default="./aa_skill_outputs")
    p_invoke.add_argument("--credit-threshold", type=float, default=5.0,
                           help="Warn if estimated remaining credit falls below this USD amount (default: 5.0).")
    p_invoke.add_argument("--skip-credit-check", action="store_true",
                           help="Bypass the pre-flight credit check for this call.")
    p_invoke.add_argument("--live-credit-probe", action="store_true",
                           help="Also fire a minimal live request to confirm the key can currently bill, "
                                "in addition to the local balance estimate.")
    p_invoke.set_defaults(func=cmd_invoke)

    p_list = sub.add_parser("list-skills", help="List registered skills.")
    p_list.set_defaults(func=cmd_list_skills)

    p_boot = sub.add_parser("bootstrap", help="Seed registry with Anthropic's pre-built document skills.")
    p_boot.set_defaults(func=cmd_bootstrap)

    p_reg = sub.add_parser("register-skill", help="Upload and register a custom AA skill bundle.")
    p_reg.add_argument("--dir", required=True, help="Path to the local SKILL.md bundle directory.")
    p_reg.add_argument("--name", required=True, help="AA-internal short name for the skill.")
    p_reg.add_argument("--title", required=True, help="Display title for the Skills API.")
    p_reg.add_argument("--description", default="")
    p_reg.add_argument("--output-kind", default=None)
    p_reg.set_defaults(func=cmd_register_skill)

    p_files = sub.add_parser("files", help="Inspect files generated within a session.")
    files_sub = p_files.add_subparsers(dest="files_command", required=True)
    p_files_list = files_sub.add_parser("list", help="List generated files in a session.")
    p_files_list.add_argument("--session", default="default")
    p_files_list.set_defaults(func=cmd_files_list)

    p_credits = sub.add_parser("credits", help="Manage local credit-balance estimation for an API key.")
    credits_sub = p_credits.add_subparsers(dest="credits_command", required=True)

    p_credits_set = credits_sub.add_parser("set-balance", help="Record your known starting balance (e.g. right after a top-up).")
    p_credits_set.add_argument("--amount", type=float, required=True, help="USD amount currently available on this key.")
    p_credits_set.set_defaults(func=cmd_credits_set_balance)

    p_credits_show = credits_sub.add_parser("show", help="Show the local estimated remaining balance.")
    p_credits_show.set_defaults(func=cmd_credits_show)

    p_credits_verify = credits_sub.add_parser("verify", help="Confirm the key is valid and can currently bill (live probe).")
    p_credits_verify.add_argument("--credit-threshold", type=float, default=5.0)
    p_credits_verify.set_defaults(func=cmd_credits_verify)

    p_sess = sub.add_parser("session", help="Inspect or reset session state.")
    sess_sub = p_sess.add_subparsers(dest="session_command", required=True)
    p_sess_show = sess_sub.add_parser("show")
    p_sess_show.add_argument("--session", default="default")
    p_sess_show.set_defaults(func=cmd_session_show)
    p_sess_reset = sess_sub.add_parser("reset")
    p_sess_reset.add_argument("--session", default="default")
    p_sess_reset.set_defaults(func=cmd_session_reset)

    return p


def main(argv: list[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
